// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ncJI_1fQdvLMoFaK7FI32lxh4FgCs1g',
    appId: '1:803437839840:web:42acf937f2348e9ee69785',
    messagingSenderId: '803437839840',
    projectId: 'engaz-task-70bc9',
    authDomain: 'engaz-task-70bc9.firebaseapp.com',
    storageBucket: 'engaz-task-70bc9.appspot.com',
    measurementId: 'G-X4N7MDL3D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqBmEYeobsbcSIUOVbiYA5Smx0iLFD1Ak',
    appId: '1:803437839840:android:4ca5b769d8492babe69785',
    messagingSenderId: '803437839840',
    projectId: 'engaz-task-70bc9',
    storageBucket: 'engaz-task-70bc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1S9Y2o7H817LBEIpwC6c47diVhnnfJ8U',
    appId: '1:803437839840:ios:a5976761c8f519e4e69785',
    messagingSenderId: '803437839840',
    projectId: 'engaz-task-70bc9',
    storageBucket: 'engaz-task-70bc9.appspot.com',
    iosBundleId: 'com.example.engazTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1S9Y2o7H817LBEIpwC6c47diVhnnfJ8U',
    appId: '1:803437839840:ios:ae2e1de10a4dcb98e69785',
    messagingSenderId: '803437839840',
    projectId: 'engaz-task-70bc9',
    storageBucket: 'engaz-task-70bc9.appspot.com',
    iosBundleId: 'com.example.engazTask.RunnerTests',
  );
}
